experiment_name: "cxr_hyda"

trainer:
  fast_dev_run: False
  max_epochs: 150
  precision: '16-mixed'
#  precision: 'bf16-mixed'
  accelerator: "gpu"
  devices:
    - 3
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "cxr_uda"
      name:
      tags:
        - hyper
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 10
        mode: "min"
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'


chkpt_callback:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    dirpath:
    filename:


model:
  class_path: chest_xray.pl_modules.DomainConditionedCXRLitModule
  init_args:
    lr: 0.001
    min_lr: 1e-6
    w_decay: 0.05 #  0.05

    # primary network
    imagenet_pretrained: True
    num_classes: 5
    task_weights: # calculated from the training set
      - 0.575
      - 0.841
      - 0.541
      - 0.797
      - 0.900
      - 0.958
      - 0.946
      - 0.230
      - 0.915
      - 0.800
      - 0.654
      - 0.823
      - 0.861
      - 1.000
      - 0.888
      - 0.930
      - 0.394
      - 0.926
    # weights for unique patients
#      - 0.621
#      - 0.836
#      - 0.631
#      - 0.874
#      - 0.880
#      - 0.985
#      - 0.959
#      - 0.310
#      - 0.901
#      - 0.764
#      - 0.538
#      - 0.868
#      - 0.906
#      - 1.000
#      - 0.851
#      - 0.903
#      - 0.231
#      - 0.904

    # domain branch
    target_domain: NIH # NIH CheXpert VinBrain
    dom_clf_ckpt: '/raid/data/users/doronser/ckpts/cxr_dom_clf_nih/cxr_dom_clf_nih_epoch=035.ckpt'#
    domain_encoder:
      class_path: chest_xray.models.domain_classifier.NaiveEncoder
      init_args:
        activation: "ReLU"
        norm_layer: "BatchNorm2d"

    domain_classifier:
      class_path: chest_xray.models.domain_classifier.NaiveClassifier
      init_args:
        num_classes: 3

    # hypernetwork
    hyper_in_size: 64
    hyper_emb: 32
    init_method: 'uniform' # uniform normal
    input_var:  1 # input CXR var: ??? domain embeddings var: ???




data:
  class_path: chest_xray.data.CXRDataModule
  init_args:
#    data_dir: "/gpfs0/tamyr/projects/data/chest_xray"
    data_dir: "/raid/data/shared_datasets/chest_xray/"
    unique_patients: False
    target_domain: NIH # NIH CheXpert VinBrain
    batch_size: 32
    num_workers: 16